# Generated by Django 6.0 on 2025-12-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.CharField(blank=True, help_text='Example: 100% Cow Milk', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodapp',
            field=models.CharField(blank=True, help_text='Example: Tea, Coffee, Daily Consumption', max_length=255, verbose_name='Product Application'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, help_text='Example: Cow Milk, Buffalo Milk', max_length=100, null=True),
        ),
    ]
